ui: tape
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: [6, 7, 8]
  - name: iphone
    version: [7.0, latest]
  - name: internet explorer
    version: [10, latest]
scripts:
  - './node_modules/pouchdb/dist/pouchdb.js'
  - './node_modules/pouchdb/dist/pouchdb.memory.js'
  - './dist/pouchdb-hoodie-api.js'
